language: python
cache: pip
matrix:
  include:
    - python: "3.5"
    - python: "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics

# command to run tests
script:
  # run unit tests
  - python -m unittest discover
  # run doctests
  - sphinx-build -M doctest doc/source doc/build
